# Generated by Django 6.0.6 on 2026-06-24 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Име на компанията')),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=5000.0, max_digits=12, verbose_name='Бюджет')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='monthly_budget',
        ),
        migrations.AddField(
            model_name='subscription',
            name='ai_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Точност на AI (%)'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Фактура (PDF/Снимка)'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_ai_extracted',
            field=models.BooleanField(default=False, verbose_name='Прочетено от AI?'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кой ползва софтуера'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Собственик / Мениджър'), ('employee', 'Служител')], default='employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Име на софтуера (напр. AWS, Slack)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(verbose_name='Дата на подновяване'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.company'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Име на отдел (напр. Маркетинг)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='subscriptions.company')),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.department'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
